# Generated by Django 5.0.3 on 2024-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Name Surname', max_length=255)),
                ('email', models.EmailField(help_text='Enter the Email Address', max_length=255)),
                ('score', models.IntegerField(help_text='Enter the score ( 10 , 20 as )')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
